-- GemQuest daily leaderboard for Supabase.
-- Run this file in the Supabase SQL editor for the project.

create table if not exists public.gemquest_daily_scores (
  id bigint generated by default as identity primary key,
  score_date date not null default ((now() at time zone 'America/Guayaquil')::date),
  level_id integer not null check (level_id between 1 and 3),
  player_id text not null check (char_length(player_id) between 1 and 128),
  player_name text not null check (char_length(player_name) between 1 and 40),
  score integer not null check (score >= 0),
  stars integer not null default 0 check (stars between 0 and 3),
  moves_left integer not null default 0 check (moves_left >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (score_date, level_id, player_id)
);

create index if not exists gemquest_daily_scores_lookup_idx
  on public.gemquest_daily_scores (score_date, level_id, score desc, stars desc, moves_left desc, created_at asc);

alter table public.gemquest_daily_scores enable row level security;

drop policy if exists "GemQuest daily leaderboard is readable" on public.gemquest_daily_scores;
create policy "GemQuest daily leaderboard is readable"
  on public.gemquest_daily_scores
  for select
  to anon, authenticated
  using (true);

grant select on public.gemquest_daily_scores to anon, authenticated;

create or replace function public.submit_gemquest_daily_score(
  p_score_date date,
  p_level_id integer,
  p_player_id text,
  p_player_name text,
  p_score integer,
  p_stars integer,
  p_moves_left integer
)
returns public.gemquest_daily_scores
language plpgsql
security definer
set search_path = public
as $$
declare
  leaderboard_timezone constant text := 'America/Guayaquil';
  saved_score public.gemquest_daily_scores;
  clean_player_id text := left(nullif(trim(p_player_id), ''), 128);
  clean_player_name text := left(coalesce(nullif(trim(p_player_name), ''), 'Jugador'), 40);
  clean_score integer := greatest(coalesce(p_score, 0), 0);
  clean_stars integer := least(greatest(coalesce(p_stars, 0), 0), 3);
  clean_moves_left integer := greatest(coalesce(p_moves_left, 0), 0);
begin
  if p_level_id < 1 or p_level_id > 3 then
    raise exception 'Nivel fuera de rango';
  end if;

  if clean_player_id is null then
    raise exception 'Jugador requerido';
  end if;

  insert into public.gemquest_daily_scores (
    score_date,
    level_id,
    player_id,
    player_name,
    score,
    stars,
    moves_left
  )
  values (
    coalesce(p_score_date, (now() at time zone leaderboard_timezone)::date),
    p_level_id,
    clean_player_id,
    clean_player_name,
    clean_score,
    clean_stars,
    clean_moves_left
  )
  on conflict (score_date, level_id, player_id)
  do update set
    player_name = excluded.player_name,
    score = excluded.score,
    stars = excluded.stars,
    moves_left = excluded.moves_left,
    updated_at = now()
  where
    excluded.score > gemquest_daily_scores.score
    or (
      excluded.score = gemquest_daily_scores.score
      and excluded.stars > gemquest_daily_scores.stars
    )
    or (
      excluded.score = gemquest_daily_scores.score
      and excluded.stars = gemquest_daily_scores.stars
      and excluded.moves_left > gemquest_daily_scores.moves_left
    )
  returning * into saved_score;

  if saved_score.id is null then
    select *
      into saved_score
      from public.gemquest_daily_scores
      where score_date = coalesce(p_score_date, (now() at time zone leaderboard_timezone)::date)
        and level_id = p_level_id
        and player_id = clean_player_id;
  end if;

  return saved_score;
end;
$$;

grant execute on function public.submit_gemquest_daily_score(
  date,
  integer,
  text,
  text,
  integer,
  integer,
  integer
) to anon, authenticated;

-- Daily reset model:
-- The game queries only rows whose score_date is today in America/Guayaquil.
-- This makes each day start with an empty ranking without deleting historical rows.
--
-- Optional cleanup if the team wants to keep only the current day:
-- delete from public.gemquest_daily_scores
-- where score_date < ((now() at time zone 'America/Guayaquil')::date);
